project_id = "nuneqhhampikooviiphf"

[functions.bulk-create-associations]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.notify-deliverable]
verify_jwt = false

[functions.moyasar-verify-payment]
verify_jwt = false

[functions.moyasar-get-config]
verify_jwt = false